Fix/425
HazyResearch/fonduer pull request #426
Opened 2020-05-21 23:44 UTC by HiromuHota

Fix #425.

2020-05-22 00:35 UTC, HiromuHota commented
`from_sentence` looks erroneous. The description (document) and the behaviour (implementation) do not seem to match.
`from_sentence` was introduced by ff42e41e422ef7a02786dc1334cdb5e3862c66e2, where `from_sentence` was called `from_phrase`.

2020-05-22 16:45 UTC, HiromuHota commented
I figured that out. `from_sentence` does what it is supposed to do. It was just confusing. I'll add comments and improve the documentation.

2020-05-26 21:08 UTC, lukehsiao requested changes

2020-05-26 21:08 UTC, lukehsiao commented on src/fonduer/utils/data_model_utils/visual.py
> +                    if (  # True if visually aligned AND not from itsself.
```suggestion
                    if (  # True if visually aligned AND not from itself.
```

2020-05-26 21:10 UTC, HiromuHota commented on src/fonduer/utils/data_model_utils/visual.py
> +                    if (  # True if visually aligned AND not from itsself.
Thanks!

2020-05-26 21:16 UTC, lukehsiao approved these changes

2020-05-26 23:14 UTC, lukehsiao commented
@HiromuHota could you squash these commits with a nice commit description, then we can merge?

2020-05-26 23:49 UTC, HiromuHota commented
I added another unit test: `test_get_ngrams_that_match_in_string` (c55295d7439893ac80ef7a926817f1e701ddbba0).
Sorry for the last minute commit!
If this looks good to you, I'll squash into one single commit.

2020-05-27 00:42 UTC, lukehsiao commented
Looks good to me!

2020-05-27 02:12 UTC, HiromuHota commented
Squashed and force-pushed.
Please merge this at your convenience.

2020-05-27 02:56 UTC, merged